hashicorp/terraform-google-terraform-enterprise

examples/root-example/main.tf

Fixed the link to the module and added an outputs block

example fixes/updates

---

README.md
files/install-ptfe.sh
variables.tf

Same as https://github.com/hashicorp/terraform-aws-terraform-enterprise/pull/13 but for GCP. This is targeted against https://github.com/hashicorp/terraform-google-terraform-enterprise/pull/11 so will need to be merged into that branch before it's merged if everything checks out.

Update Custom Weave/Replicated CIDR variables for new ptfe flags

---

files/install-ptfe.sh
variables.tf

jq is not in the RHEL repos - added a line to the installer to grab the binary from github.

Jq fix rhel

---

examples/rhel-production-example/main.tf
examples/root-example/README.md
examples/root-example/main.tf

Sorry for the delays on these! This updates the examples found to leverage the GA versions and language.

Update examples to use GA release

---

docs/inputs.md
examples/rhel-production-example/main.tf
examples/root-example/main.tf
files/install-ptfe.sh
variables.tf

If repl_cidr is set, it needs to be added to the no_proxy list. (https://app.asana.com/0/157256879238414/1150495725947889/f)
Also made some updated to the README and examples regarding the autoscaling change.

No proxy fix and docs update

---

.github/ISSUE_TEMPLATES/Bug_Report.md
.github/ISSUE_TEMPLATES/config.yaml
.github/pull_request_template.md

Adding PR Template, Bug Report Issue template and link for security vulns
These were gratuitously stolen from the providers-terraform-aws repo
No tests for templates

Add templates

---

examples/rhel-production-example/main.tf
examples/root-example/main.tf

Updated the version in the examples to reference pending release v0.1.2

update examples with appropriate version

---

modules/configs/templates/replicated/replicated-ptfe.conf

Removed demo(poc) and changed to internal production.
As discussed on zoom, rolling the IPM change into the v0.12 reroll code. 
Built a cluster!
* Terraform Version: 0.12.21

Update to work with IPM

---

README.md
examples/root-example/main.tf
versions.tf

This branch updates the README with a definition of the Quickstart Method and clarification of the different usage methods.
Relates #38 
[Asana task](https://app.asana.com/0/1170474914009329/1157300874913655/f)

Update README usage methods

---

README.md
examples/proxy/main.tf
examples/root-example/main.tf
examples/shared-vpc/main.tf
examples/shared-vpc/modules/host/main.tf
examples/shared-vpc/modules/service/main.tf

In anticipation of requesting reviews on the `internal-preview` branch, this branch updates the README and the example module sources to use the `internal-preview` branch from GitHub in order to reduce confusion about expected usage.
[Asana task](https://app.asana.com/0/1173034859097128/1173938016368947/f)
I ensured that the updated examples could still download the modules successfully.
* Terraform Version: 0.12.17, 0.12.24

Update for internal preview usability

---

README.md

This branch fixes the URL for the `LICENSE` file in the README.

Fix LICENSE URL in README

---

.github/workflows/auto.yml
.tflint.hcl

This branch adds a workflow to perform linting and formatting checks on pull requests for all Terraform files in the repository.
[Asana task](https://app.asana.com/0/1181500399442529/1200449299638584/f)
To be tested post-merge and addressed accordingly.

Add workflow to check formatting and linting

---

.github/workflows/dispatcher.yml
.github/workflows/handler-destroy.yml
.github/workflows/handler-help.yml
.github/workflows/handler-test.yml

This branch adds the various workflows that enable us to test the module, similar to terraform-aws-terraform-enterprise!
[Asana task](https://app.asana.com/0/1181500399442529/1200449299638592/f)
It will be tested post-merge.

Add testing workflows

---

.github/workflows/handler-destroy.yml

This branch updates the format of the report from running `/destroy` in pull requests.
Relates #86

Update destroy report

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This branch adds handlers for the private-tcp-active-active test scenario.
This will be tested post-merge by a follow-up pull request.

Add test handler for private-tcp-active-active

---

main.tf
modules/redis/main.tf
modules/redis/variables.tf
tests/private-active-active/main.tf
tests/private-tcp-active-active/main.tf
tests/public-active-active/main.tf
variables.tf

This branch adds labels (aka tags) to resources for the test modules and creates a variable for labels for the root module.
[Asana Task](https://app.asana.com/0/1181500399442529/1200356536468561/f)
Planned locally. Will test here.

add label values for test modules

---

main.tf
modules/database/main.tf
modules/redis/outputs.tf
modules/user_data/main.tf
modules/user_data/templates/tfe_vm.sh.tpl
modules/user_data/variables.tf
variables.tf

This branch removes empty string logic in the variables.
[Asana Task](https://app.asana.com/0/1200094219584695/1200633149600285/f)
Validated and Planned locally

remove empty string logic

---

main.tf
modules/database/variables.tf
modules/networking/variables.tf
modules/redis/variables.tf
modules/user_data/variables.tf
variables.tf

This branch removes all of the default variable values in the submodules and moves them to the root module when appropriate. 
[Asana Task](https://app.asana.com/0/1181500399442529/1201041474324382/f)
Planned locally. Testing here.

remove default values in submodules

---

variables.tf

This branch updates the default PostgreSQL version to 12.
[Asana task](https://app.asana.com/0/1135304898243667/1201068889880687/f)
It will be tested here!

PostgreSQL 12

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This branch updates the test and destroy workflows to configure a transient workspace for the Public Active/Active test.
This will be tested in https://github.com/hashicorp/terraform-google-terraform-enterprise/pull/120.

Configure transient workspace for Public Active/Active

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This branch fixes the sed syntax that replaces the module source.
Relates #122 
To be tested in #120.

Fix sed syntax

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This branch updates the test workflows for the Private Active/Active and Private TCP Active/Active tests to assume transient workspaces are used.
Relates #119
In #120.

Assume transient workspaces in all tests

---

.github/workflows/handler-test.yml
.gitignore
tests/private-active-active/data.tf
tests/private-active-active/main.tf
tests/private-active-active/providers.tf
tests/private-active-active/variables.tf
tests/private-active-active/versions.tf
tests/private-tcp-active-active/data.tf
tests/private-tcp-active-active/main.tf
tests/private-tcp-active-active/providers.tf
tests/private-tcp-active-active/variables.tf
tests/private-tcp-active-active/versions.tf
tests/public-active-active/data.tf
tests/public-active-active/locals.tf
tests/public-active-active/main.tf
tests/public-active-active/providers.tf
tests/public-active-active/variables.tf
tests/public-active-active/versions.tf

This branch updates the module CI tests to use transient workspaces associated with the pull request number.
Relates #119
...
* Terraform Version: 1.0.11

Use transient workspaces for tests

---

examples/proxy/README.md
examples/shared-vpc/README.md

Related to #129 
This changes the URLs in the examples, too.

correct source urls

---

fixtures/secrets/README.md
fixtures/secrets/locals.tf
fixtures/secrets/main.tf
fixtures/secrets/outputs.tf
fixtures/secrets/variables.tf
fixtures/secrets/versions.tf
modules/user_data/templates/tfe_vm.sh.tpl
tests/standalone-external-rhel8-worker/main.tf
tests/standalone-mounted-disk/main.tf

This PR adds a secrets fixture module and updates the nightly build tests to use it.
It was tested with the backing configuration for the module CI tests. The tests here will consume those new secrets.

Add secrets fixture

---

.github/workflows/auto.yml
.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This PR updates the workflows to lint the `fixtures` directory and to update fixture module source references in tests so that they are resolvable from TFC.
Relates #135
It will be tested by #135.

Lint and source fixtures

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This PR fixes the module source adjustment for `fixtures/test_proxy` in the test handler jobs.
Relates #136
I manually tested the sed logic. It shall also be tested in #135.

Fix source adjustment for fixtures/test_proxy

---

fixtures/test_proxy/locals.tf
fixtures/test_proxy/main.tf
fixtures/test_proxy/outputs.tf

This PR follows up on #135 as it did not account for selecting between mitmproxy and Squid.
Tested here!

Switch between mitmproxy and Squid

---

.github/workflows/handler-help.yml

Asana: https://app.asana.com/0/1200681690870921/1202309885053135/f
Relates: 
* https://github.com/hashicorp/terraform-random-tfe-utility/pull/34
* https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/172
* https://github.com/hashicorp/terraform-aws-terraform-enterprise/pull/252
Tested here: https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/173#issuecomment-1136185275

add test case names to /help

---

.github/workflows/handler-test.yml

[ASANA](https://app.asana.com/0/1201666209480314/1202378337620629/f)
Need to be on main branch for testing.

 /test handler erroring on terraform-random-tfe-utility feature branches

---

.github/workflows/handler-pr-close.yml

Update on [PR](https://github.com/hashicorp/terraform-google-terraform-enterprise/pull/168)

fixing quotes

---

.github/workflows/handler-pr-close.yml

[PR payload ](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request:~:text=public-,pull_request,-pull_request_review)is used for data fetching

PR Handler : no client payload, data fetched from PR payload

---

.github/workflows/handler-pr-close.yml

Small change to fix how env var is used

env vars are not normal vars

---

.github/workflows/handler-pr-close.yml
tests/standalone-external-rhel8-worker/main.tf
tests/standalone-external-rhel8-worker/variables.tf
tests/standalone-mounted-disk/main.tf
tests/standalone-mounted-disk/variables.tf
variables.tf

This is a prerequisite for making this test available in utility-repo-ci.
CircleCI [ptfe-replicated test](https://app.circleci.com/pipelines/github/hashicorp/ptfe-replicated/4248/workflows/232d82b2-01ea-4835-9f14-47692fc1525d)

removing tfe license as secret

---

tests/private-active-active/run-tests.sh
tests/private-tcp-active-active/run-tests.sh
tests/public-active-active/run-tests.sh

dig the ip of env only for public tests

No proxy for public tests

---

tests/standalone-external-rhel8-worker/run-tests.sh
tests/standalone-mounted-disk/run-tests.sh

run-tests.sh for standalone test.
aligning terraform output with run-tests.sh

update for standalone

---

.github/workflows/handler-test.yml

Adding `terraform_wrapper: true` 
Setting it to false cause errors in reading data output

wrapper set true

---

.github/workflows/handler-test.yml
fixtures/test_proxy/versions.tf

update hashicorp/setup-terraform@v2 and terraform_version: 1.1.7

Test GHA with hashicorp/setup-terraform@v2

---

tests/private-active-active/run-tests.sh
tests/private-tcp-active-active/run-tests.sh
tests/public-active-active/run-tests.sh
tests/standalone-external-rhel8-worker/run-tests.sh
tests/standalone-mounted-disk/run-tests.sh

THis is an attempt to run-tests.sh without terraform output cli

run-tests update for all tests

---

.github/workflows/create-jira-issue.yml

Need to update the jira workflows to take parameters and run with PR from external contributors.

update jira call

---

.github/workflows/create-jira-issue.yml

Let's try this one more time (re: #222 ), this time without the copy/pasta mistake that uses a local path for the workflow.

update workflow path

---

tests/standalone-external-rhel8-worker/data.tf

Use newer RHEL image.
N/A
N/A
N/A

Use newer RHEL image for tests

---

tests/standalone-external-rhel8-worker/data.tf

We have been seeing [this test](https://github.com/hashicorp/ptfe-replicated/actions/runs/4347605718/jobs/7595148141) fail consistently, so I would like to update the image and test again.
Will be tested in ptfe-replicated CI, which is failing anyway.

update RHEL8 image version for worker test

---

tests/standalone-mounted-disk/main.tf
tests/standalone-mounted-disk/variables.tf

Plumbing through consolidated services to the mounted disk test.
By running this test!
N/A
N/A

Update mounted disk test to support consolidated services

---

tests/private-active-active/main.tf
tests/private-active-active/variables.tf
tests/private-tcp-active-active/main.tf
tests/private-tcp-active-active/variables.tf
tests/public-active-active/main.tf
tests/public-active-active/variables.tf
tests/standalone-external-rhel8-worker/variables.tf
tests/standalone-mounted-disk/main.tf
tests/standalone-mounted-disk/variables.tf

This branch adds the `consolidated_services` variable defaulted to `false` to the tests.

add consolidated_services var to tests

---

.github/workflows/handler-pr-close.yml
.github/workflows/handler-test.yml

#240 
Somewhere along the way the logic for using ephemeral workspaces got completely broken. This is the first attempt to try and fix the workflows, but as I need to commit to `main` to test them, it may take a little while.

fix workspace destroy

---

.github/workflows/handler-destroy.yml

This fixes a typo in the token name.

fix token name

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-help.yml
.github/workflows/handler-test.yml
locals.tf
tests/private-active-active/data.tf
tests/private-tcp-active-active/data.tf
variables.tf

Related to https://github.com/hashicorp/terraform-random-tfe-utility/pull/131
[Jira TF-8611](https://hashicorp.atlassian.net/browse/TF-8611)
This branch implements the reusable workflows introduced [here](https://github.com/hashicorp/terraform-random-tfe-utility/pull/131). 
The branch of the reusable workflows that these workflows are using is [this one](https://github.com/hashicorp/terraform-random-tfe-utility/pull/133) and will be changed back to `main` after all of the testing for this [story](https://hashicorp.atlassian.net/browse/TF-8611) is complete.

Use reusable workflows

---

tests/private-active-active/versions.tf
tests/private-tcp-active-active/versions.tf
tests/standalone-external-rhel8-worker/versions.tf
tests/standalone-mounted-disk/versions.tf

Upgrading Google provider version.
Already tested in other test repos.

Upgrade tests module google provider version to ~> 5.0

---

outputs.tf

Adding object store details to output
[Jira TF-11115](https://hashicorp.atlassian.net/browse/TF-11115)
[Jira TF-11116](https://hashicorp.atlassian.net/browse/TF-11116)
[Jira TF-11117](https://hashicorp.atlassian.net/browse/TF-11117)

TF-11115, TF-11117, TF-11116] Adding object store details to output
