primary.tf
variables.tf

Optional variable added 'dns_project' which, if specified, will override the default project for the google_dns_managed_zone data source and the google_dns_record_set resource for creading dns entries for the primary instances.

added option to specify a project for the dns zone

---

primary.tf
secondary.tf
variables.tf

Force 3 primary nodes if mode is internal production, due to scaling issue with ceph, otherwise use count value.

Primary nodes

---

README.md
files/install-ptfe.sh
modules/instance-template/README.md
modules/instance-template/secondary.tf
modules/instance-template/variables.tf
primary.tf
variables.tf

Related to https://github.com/hashicorp/terraform-aws-terraform-enterprise/pull/17
Quoting that issue: 
> This PR fixes an issue where the ca_cert_url would error out while trying to retrieve it.
> 
> There were two problems:
> 
> 1. It attempted to use `/tmp/ptfe/customer-certs` as a working dir, but the downloaded `ptfe` tool was still in the `/tmp` dir causing it to collide and error out.
> 2. `wget` was passed an arg it did not recognize.
> 
> Couple quick fixes and it works! 🎉
> 
> Part 2 of this PR is something that's easy to revert and I'm open to it this late in the game but I changed the variable to `ca_bundle_url`. I did this to better match the terminology we use in the settings UI and to denote that this can be a whole bundle and not just a single cert.
> 
> These fixes may …

Fix Custom CA bundle install, rename ca_cert_url to ca_bundle_url

---

files/install-ptfe.sh
variables.tf

Piping through the `--airgap` flag in the install script to properly setup airgap cluster.
Also added back in ubuntu 18.04 due to fix in ptfe tool.

Airgap fix and add ubuntu 18.04 back as default

---

files/install-ptfe.sh

Related to https://github.com/hashicorp/terraform-aws-terraform-enterprise/pull/22
>Came up in testing where other nodes could not join the cluster as they were attempting to setup a custom ca bundle which mutates the replicated-ptfe.conf but that file is only placed on the first server (which we refer to as "main" in the scripts).
>
>This PR moves the setup of the bundle into the area of setup that only runs on main which fixes the issue.

Only run the Custom CA Bundle setup function on the main server

---

secondary.tf
variables.tf

This PR modifies the secondaries to be part of an autoscaling group. This removes the 'secondary_count' variable, and adds 'min_secondaries' and 'max_secondaries', with default values of 1 and 3, respectively. README and examples have been updated to reflect this.

Add the prefix to the name of the secondary instance group

---

secondary.tf

The autoscaler did not have a prefix on the name - added it to bring it in line with all the other resources.
Ran tests against ptfeacc-test w/a local copy w/o error. 
* Terraform Version: v0.11.14
* Any additional relevant variables: used default values for min/max secondaries.

add prefix to the autoscaler name

---

modules/cluster/modules/internal_lb/proxy.tf
modules/lb/main.tf

These are the two resources I found trying to create a second installation in a single project. The ternary in count for the policy creation I noticed while fixing the names. I'm not sure if you want to start adding those at the moment.
I was able to install a second installation in a single project with no further errors.
* Terraform Version: 12.17

Uniquely name internal proxy health check and ssl policy

---

main.tf
variables.tf

Currently `min_secondaries` defaults to `0` but it's not exposed for use by the top level module.
I modified a running cluster with an increased secondary count and they were created and successfully joined the cluster.
* Terraform Version: 12.17

Expose cluster secondary scaling variables to top level module

---

main.tf
modules/postgres/main.tf
modules/postgres/variables.tf
variables.tf

Enable selecting `REGIONAL` availability type
Enable automated backup configuration
Expose higher availability options for the postgresql module
I modified a running cluster and the settings were added correctly. I have not yet tried to downgrade the instance or disable backups.
* Terraform Version: 12.7

Additional postgresql options

---

README.md
examples/root-example/main.tf
examples/root-example/outputs.tf
examples/root-example/variables.tf
examples/root-example/versions.tf
modules/cluster/outputs.tf

This branch is primarily focused on updating root-example to be compatible with the re-rolled module, but it also documents the required GCP permissions and fixes a bug with the `installer_dashboard_url` output.
Relates to #38.
I created and destroyed root-example.
* Terraform Version: 0.12.19

Root example re-roll

---

main.tf
modules/cluster/module-internal-lb.tf
modules/cluster/modules/internal_lb/main.tf
modules/cluster/modules/internal_lb/variables.tf
modules/cluster/primary.tf
modules/cluster/variables.tf

This branch replaces the use of data sources with a direct resource reference to provide the network name to different resources. Resources which depend on data sources for the network name can cause the following error upon destroy:
> "network": required field is not set
Relates to #38.
After making this change, I was able to create and destroy root-example without receiving the required field error.

Depend on network resource rather than data source

---

main.tf
modules/cluster/module-internal-lb.tf
modules/cluster/modules/internal_lb/main.tf
modules/cluster/modules/internal_lb/proxy.tf
modules/cluster/modules/internal_lb/variables.tf
modules/cluster/primary.tf
modules/cluster/secondary.tf
modules/cluster/variables.tf
modules/vpc/outputs.tf

Similar to #46, this commit replaces the remaining instances of subnetwork
data sources with a reference to the subnetwork resource to prevent the following
error on destroy:
> Error: Null value found in list
>
>  on ../../modules/cluster/modules/internal_lb/main.tf line 91, in
> resource "google_compute_firewall" "internal-ilb-fw":
>  91:   source_ranges =
> [data.google_compute_subnetwork.internal.ip_cidr_range]
>
> Null values are not allowed for this attribute value.
Relates to #46, #38 
Provisioned and destroyed root-example without experiencing the previously mentioned error.

Replace subnet data sources with resource references

---

main.tf

There is a bug in Terraform which results in cycles during the destroy command [1].
A workaround for the bug is to reference specific module outputs rather than whole modules.
[1]: https://github.com/hashicorp/terraform/issues/21662#issuecomment-503206685
Relates #38 
I applied and destroyed `examples/root-example` with the source altered to reference the `f-reroll` branch.

Resolve destroy cycles

---

locals.tf
main.tf
modules/dns/main.tf
modules/dns/variables.tf
variables.tf

Allow managed dns zone to be in another project.
Installed TFE from scratch with this branch for both cases of single project and separate dns project.

Allow overriding project for managed dns zone

---

modules/lb/forwarding_rule.tf

There's a syntax error in variable ssl_certificates.
Uncomment and run terraform init.

fixed syntax error

---

.scripts/doc-gen.sh

Google version of what I did over in hashicorp/terraform-aws-terraform-enterprise#67 .
Too link didn't click; This script updates the doc-gen.sh script with a newer binary and updates the flags to match as the older one was breaking. 
In the case of this one and not the others I decided to not generate new docs as https://github.com/hashicorp/terraform-google-terraform-enterprise/pull/38 is still in flight and changes things significantly. 
We will want to cherry pick this change into #38. 
Confirmed it ran locally, but then discarded the results so it could be better applied to the reroll.

Update doc-gen.sh script to newer binary

---

docs/inputs.md
main.tf
modules/internal-load-balancer/docs/inputs.md
modules/internal-load-balancer/main.tf
modules/internal-load-balancer/variables.tf
modules/postgresql/docs/inputs.md
modules/postgresql/variables.tf
modules/storage/docs/inputs.md
modules/storage/variables.tf
variables.tf

Users of the module require the ability to apply labels to the resources which are created. I audited all of the resources and verified that the `f-reroll` branch currently supports labelling of all applicable resources except for the internal-load-balancer compute instance template. This branch adds the missing labels to that template and a root variable to assign labels globally.
Relates #38 
I adjusted the root module example to source the root module and verified that a plan could be generated.

Add labels argument to root and internal-load-balancer

---

examples/proxy/main.tf

The proxy example was not updated when the Shared VPC changes were merged. This branch updates the example.
Relates #38 
I updated the module sources in the example to use local filesystem references and then followed the instructions in the README.
* Terraform Version: 0.12.24

Update proxy example based on Shared VPC changes

---

modules/external-load-balancer/main.tf

Requesting a support bundle results in an 5XX series error. This branch increases the connection timeout for the install dashboard in order to allow support bundle requests to be properly processed.
Relates #38 
[Asana task](https://app.asana.com/0/1168960898522641/1172263022406361/f)
I updated the root example to source the root module from the filesystem, deployed the example cluster, and verified that I could download a support bundle.

Increase dashboard timeout to 5 minutes

---

examples/proxy/main.tf
examples/shared-vpc/modules/service/main.tf
main.tf
modules/external-load-balancer/docs/inputs.md
modules/external-load-balancer/main.tf
modules/external-load-balancer/variables.tf
modules/internal-load-balancer/docs/inputs.md
modules/internal-load-balancer/main.tf
modules/internal-load-balancer/variables.tf
modules/primaries/docs/outputs.md
modules/primaries/main.tf
modules/primaries/outputs.tf

Users have requested that all compute instance groups be deployed in a regional manner to improve redundancy and disaster mitigation. The primaries were the only group which were not already deployed in this manner; this branch changes that.
Relates #38 
[Asana task](https://app.asana.com/0/1170474914009329/1156584069212417/f)
I deployed the root example with the source altered to the local pathname of the root module. I verified that the pods came up correctly and each primary was deployed to a different zone.

Deploy primaries in regional manner

---

modules/cloud-init/docs/inputs.md
modules/cloud-init/files/install-ptfe.sh
modules/cloud-init/main.tf
modules/cloud-init/templates/base-cloud-config.yaml.tmpl
modules/cloud-init/variables.tf

Users have requested the ability to inject custom commands in to `install-ptfe.sh`. This branch adds ~a variable which defines a custom shell script to be executed prior to invoking `ptfe install`~ variables which define a pre-install script and post-install script which are executed at the beginning and the end of `install-ptfe.sh`.
[Asana task](https://app.asana.com/0/1170474914009329/1158789214132833/f)
I deployed TFE using the root example and verified that the default ~custom script was~ scripts were executed on multiple compute instances.

Add hooks for pre-install script and post-install script to install-ptfe.sh

---

docs/inputs.md
main.tf
modules/internal-load-balancer/main.tf
modules/postgresql/docs/inputs.md
modules/postgresql/variables.tf
modules/primaries/main.tf
variables.tf

This branch includes miscellaneous updates which align the module with terraform.io documentation.
- add secondary count inputs to the root module
- deploy PostgreSQL regionally
- consistently uncapitalize "primary" and "secondary", except for names
- rename ILB "nodes" to "routers" for clarity (not documentation related)
I provisioned an environment using the root module.

Miscellaneous updates to align with documentation

---

docs/inputs.md
main.tf
modules/cloud-init/templates/replicated.conf.tmpl
modules/internal-load-balancer/docs/inputs.md
modules/internal-load-balancer/versions.tf
variables.tf

Need to pass a root module variable down to the `cloud-init` module so
that a user can pin the release sequence. Also the value of the
`ReleaseSequence` attribute in the `/etc/replicated.conf` file needs
to be unquoted since it's a JSON number, not a string.
Using the `examples/root` configuration.
- Terraform 0.12.28
```
provider "google" {
version     = "3.21.0"
credentials = file("~/redacted")
project     = "redacted"
region      = "redacted"
}
provider "google-beta" {
version     = "3.21.0"
credentials = file("~/redacted")
project     = "redacted"
region      = "redacted"
}
provider "random" {
version = "2.1.0"
}
provider "template" {
version = "2.1.0"
}
module "terraform_enterprise" {
source = "github.com/hashicorp/terraform-google-terraform-enterprise?ref=sudomateo-sequence-pinning" …
```

Fix pinning release sequence

---

modules/cloud-init/files/install-ptfe.sh

Logic to configure the exec-opts of the Docker daemon was added to [ptfe v0.20.0](https://github.com/hashicorp/ptfe/pull/79/files?file-filters%5B%5D=.go#diff-2867dfb8ef216abdf46fa974bbfa957fR1624-R1626). Similar logic was already added to this module, and now this implementation conflicts with ptfe and prevents it from setting up a new cluster.
~Testing will commence shortly.~ We redeployed the compute instances of a broken deployment with this patch and saw them start the cluster successfully.
* Terraform Version: 0.12

Drop config of Docker daemon from install-ptfe.sh

---

main.tf
modules/user_data/main.tf
modules/user_data/variables.tf
variables.tf

This allows the user to pass the release sequence and pin their installation to a specific version of Terraform
Enterprise.
By spinning up Terraform Enterprise via the `active/active` example.
The `active/active` example.

Add ability to specify release sequence

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This branch adds support for `/test private-active-active`, based on the AWS module system. Notable differences include:
- the use of the setup-gcloud action to configure cloud credentials, rather than the configure-aws-credentials action
- the use of the gcloud CLI to create the SOCKS5 proxy, rather than the aws CLI.
This will be tested in a subsequent PR that implements the test configuration.

Add /test private-active-active

---

.github/workflows/handler-test.yml

This branch fixes a reference to `steps.retrieve-instance-name` in the private-active-active test handler.

Fix reference to retrieve-instance-name

---

.github/workflows/handler-test.yml

This branch retrieves the instance zone from the Terraform outputs and configures gcloud for noninteractive use.

Retrieve instance zone; noninteractive gcloud

---

.github/workflows/handler-test.yml

This branch adds the `-f` flag to the `gcloud compute ssh` command so that the associated process is placed in the background and the rest of the workflow may proceed.

Put ssh in background

---

.github/workflows/handler-test.yml

This branch increases the wait for TFE in the private-active-active test to 25 minutes, to account for the very slow installation time on RHEL.

Increase wait-for-tfe to 25 minutes

---

.github/workflows/handler-test.yml

This branch drops `iact_subnet_list` from the `private-active-active` handler as the value must be set within configuration to include only the IP address of the HTTP proxy instance.

Drop iact_subnet_list from private-active-active

---

.github/workflows/handler-test.yml

This branch fixes the TFC token used for the private-tcp-active-active test job.
This will be tested in #96.

Fix TFC token for private-tcp-active-active

---

.github/workflows/handler-test.yml

Currently, if a `::set-output` command sets a value to be the output of a `curl` command that fails, the value is set to an empty string. This branch changes it so that the `curl` output is stored in a variable first, and then the `::set-output` command uses the variable. This way, if `curl` fails, the build will fail.
[Asana Task](https://app.asana.com/0/1181500399442529/1200819228490425/f)
I used a poc repo and first ran the existing logic [here](https://github.com/anniehedgpeth/hello-world-composite-run-steps-action/runs/3691375331?check_suite_focus=true#step:5:1), which does not fail (reproducing the problem).
I added the variable logic [to this build](https://github.com/anniehedgpeth/hello-world-composite-run-steps-action/runs/3691354714?check_suite_focus=true#step:5:1), and it …

use vars for set-output values so that they fail

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This branch fixes the reference to the GitHub pull request number to account for the indirection of the dispatch/handler model.
To be tested in #120.

Read dispatch payload for issue number

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This branch has 2 fixes.
First, it dynamically updates the TFE module source from a local pathname to a GitHub reference to the same repository and commit. This is necessary because the transient workspaces have no working directory, which means only the local working directory is uploaded to TFC and the required root module is omitted.
Second, it configures the tfe and google providers using Terraform variables as environment variables are not propagated from GHA to TFC.
This will be tested in #120.

Update module source and configure providers

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This branch updates the github.auto.tfvars files for the Public Active/Active test to directly include the contents of GOOGLE_CREDENTIALS by using heredocs. This avoids the HCL escaping issue caused by the value's JSON content.
Relates #122
In #120.

Fix Google Credentials in PAA test

---

locals.tf

This change should fix the following error:
```
Error: Inconsistent conditional result types
on ../../locals.tf line 29, in locals:
29:     local.private_load_balancing_enabled ? google_compute_address.private : google_compute_global_address.public
├────────────────
│ google_compute_address.private is a list of object, known only after apply
│ google_compute_global_address.public is a list of object, known only after apply
│ local.private_load_balancing_enabled is a bool, known only after apply
The true and false result expressions must have consistent types. The given expressions are list of object and list of object, respectively.
```
Used the module to spin up a Terraform Enterprise installation that was previously failing.
N/A
N/A

Use consistent types on both conditional paths

---

README.md

Have a ticket wherein customer is using this module. I noticed that the README example contains a reference to the old GitHub repo name.
N/A, just a doc change.

README: Fixup repo URL

---

main.tf
variables.tf

This PR adds a variable to control the size of the mounted disk used in Mounted Disk mode.
Asana task: https://app.asana.com/0/1181500399442529/1201474260744977/f
We will only rely on the Terraform validity check as this is a simple refactor from a hard-coded value to a variable with an equivalent default value.

Add var.vm_mounted_disk_size

---

modules/user_data/templates/tfe_vm.sh.tpl
modules/user_data/variables.tf
variables.tf

This PR finishes the initial implementation of airgap support.
Some assumptions that will need to be revisited when this use case is better understood:
- `airgap_url` is expected to be an HTTPS URL for an airgap package, like the ones provided by the Replicated vendor portal.
- Docker can be installed by package manager
- Replicated [states](https://community.replicated.com/t/installing-docker-in-airgapped-environments/81) most customers use repository mirrors
- Ubuntu deployments can reach download.docker.com to obtain the Docker GPG key
Asana task: https://app.asana.com/0/1181500399442529/1201475371010432/f
Successfully deployed an airgap package using our internal development workflow.

Finish initial implemenation of airgap support

---

main.tf
modules/service_accounts/locals.tf
modules/service_accounts/main.tf
modules/service_accounts/outputs.tf
modules/service_accounts/variables.tf
variables.tf

This change adds an optional variable, override_service_account_id, that prevents terraform from creating a new service account for logging purposes and instead uses the provided service account. This impacts the identity used for logging from the firewall and compute cloud objects. When a service account id is provided a data block is used to pull the account data and is transparently passed to the output of the service account sub-module.
This branch was used to generate an operational TFE instance in a GCP project with IAM management disallowed. This TFE instance was fully operational and applied completely.  GCP tests will be executed on this pull request to handle negative testing.
* Terraform Version: 1.0.11
* Any additional relevant variables: NA

Optional service account

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml
README.md
tests/private-active-active/main.tf
tests/private-active-active/variables.tf
tests/private-tcp-active-active/main.tf
tests/private-tcp-active-active/variables.tf
tests/public-active-active/main.tf
tests/public-active-active/variables.tf

This change adds the existing_service_account_id variable to support a move to the new testing projects.
These changes have been tested in the development environment to successful instance deployment. Testing automation on this repository will confirm the functionality in the new project.

GCP testing project move changes

---

.github/workflows/handler-test.yml

Test runs are timing out on the current combination of RHEL 7 and yum cache status. This change bumps that timeout higher to give terraform enterprise the time to safely initialize.
No substantive change to module code

Upping the wait time on TFE init

---

examples/standalone-airgap-dev/README.md
examples/standalone-airgap-dev/main.tf
examples/standalone-airgap-dev/outputs.tf
examples/standalone-airgap-dev/terraform.tfvars.example
examples/standalone-airgap-dev/variables.tf
examples/standalone-airgap-dev/versions.tf

Asana: https://app.asana.com/0/1181500399442529/1202138985475044/f
This branch adds a `standalone-airgap-dev` example which assumes that you really just want to test the airgap bundle and want to install the prereqs alongside the installation.
I tested this locally and put screenshot in the [Asana task](https://app.asana.com/0/1181500399442529/1202138985475044/f).

add airgap dev example

---

.github/workflows/handler-test.yml

As tested here, the checkout does not need the ref: https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/165

remove ref to master

---

main.tf
variables.tf

Removing the demo (`poc`) installation mode to get ready for the April release of Terraform Enterprise where it will be removed in the code.
This should not get merged until after the April release of Terraform Enterprise is released.
Tested this by building a mounted disk installation of a development Terraform Enterprise version.
CI/CD

 TF-440: Remove demo (poc) mode

---

.github/workflows/handler-test.yml
.gitignore
tests/private-active-active/versions.tf
tests/private-tcp-active-active/versions.tf
tests/public-active-active/versions.tf
tests/standalone-external-rhel8-worker/data.tf
tests/standalone-external-rhel8-worker/main.tf
tests/standalone-external-rhel8-worker/providers.tf
tests/standalone-external-rhel8-worker/variables.tf
tests/standalone-external-rhel8-worker/versions.tf
tests/standalone-mounted-disk/data.tf
tests/standalone-mounted-disk/main.tf
tests/standalone-mounted-disk/providers.tf
tests/standalone-mounted-disk/variables.tf
tests/standalone-mounted-disk/versions.tf

Moving internal tests to the new managed projects has highlighted a few hardcoded elements in the standalone* test cases.  This change introduces output reads from the base resource TFE workspace to obviate the need to maintain these values over time / through certificate rotations.
Both standalone test instances have been executed to completion locally.

Making standalone test cases dynamic in their base resource config

---

.github/workflows/handler-pr-close.yml

This PR includes changes that fix the error when running `terraform workspace list` against TFC.
Error: 
```
terraform workspace list  | grep -cx google-private-tcp-active-active-
workspaces not supported
0
```
Added GHA for other test as well.

update on PR-Close-Handler

---

tests/private-active-active/data.tf
tests/private-active-active/locals.tf
tests/private-active-active/providers.tf
tests/private-active-active/variables.tf
tests/private-tcp-active-active/data.tf
tests/private-tcp-active-active/locals.tf
tests/private-tcp-active-active/providers.tf
tests/private-tcp-active-active/variables.tf
tests/public-active-active/data.tf
tests/public-active-active/locals.tf
tests/public-active-active/providers.tf
tests/public-active-active/variables.tf
tests/public-active-active/versions.tf
tests/standalone-external-rhel8-worker/data.tf
tests/standalone-external-rhel8-worker/locals.tf
tests/standalone-external-rhel8-worker/providers.tf
tests/standalone-external-rhel8-worker/variables.tf
tests/standalone-mounted-disk/data.tf
tests/standalone-mounted-disk/locals.tf
tests/standalone-mounted-disk/providers.tf
tests/standalone-mounted-disk/variables.tf
tests/standalone-mounted-disk/versions.tf

Changing input vars to string for creating TFE workspaces for tests as workspace only accept string var.
[circle CI tests
](https://app.circleci.com/pipelines/github/hashicorp/ptfe-replicated/4270/workflows/2aad9c13-9e19-460e-95a0-a783017e4c04)

TFE workspace only accepts string

---

tests/private-active-active/run-tests.sh
tests/private-tcp-active-active/run-tests.sh
tests/public-active-active/run-tests.sh

Adding sleep time before run-tests for ssh tunneling to settle in

add sleep time before run-tests.sh

---

tests/standalone-external-rhel8-worker/locals.tf
tests/standalone-external-rhel8-worker/main.tf
tests/standalone-mounted-disk/locals.tf
tests/standalone-mounted-disk/main.tf

Using locals (similar to AWS mod) to set value for count in secret fixture as this value cannot be null.
Error: Invalid function argument
on main.tf line 10, in module "secrets":
10:   count  = length(var.license_file)
├────────────────
│ var.license_file is null
Invalid value for "value" parameter: argument must not be null.

null value not setting default

---

.github/workflows/handler-test.yml
tests/private-active-active/versions.tf
tests/private-tcp-active-active/versions.tf
tests/public-active-active/versions.tf
tests/standalone-external-rhel8-worker/data.tf
tests/standalone-external-rhel8-worker/locals.tf
tests/standalone-external-rhel8-worker/main.tf
tests/standalone-external-rhel8-worker/run-tests.sh
tests/standalone-external-rhel8-worker/variables.tf
tests/standalone-external-rhel8-worker/versions.tf
tests/standalone-mounted-disk/data.tf
tests/standalone-mounted-disk/locals.tf
tests/standalone-mounted-disk/main.tf
tests/standalone-mounted-disk/run-tests.sh
tests/standalone-mounted-disk/variables.tf
tests/standalone-mounted-disk/versions.tf

`var.tfe_license_secret_id` is not used by both ptfe-replicated circle CI and the terraform-random-tfe-utility GHA tests.
license is fetched either from secret fixture module or via TFE provider data block

Error null

---

tests/private-active-active/main.tf
tests/private-tcp-active-active/main.tf
tests/public-active-active/main.tf
tests/standalone-external-rhel8-worker/data.tf
tests/standalone-external-rhel8-worker/locals.tf
tests/standalone-external-rhel8-worker/main.tf
tests/standalone-external-rhel8-worker/outputs.tf
tests/standalone-mounted-disk/data.tf
tests/standalone-mounted-disk/locals.tf
tests/standalone-mounted-disk/main.tf
tests/standalone-mounted-disk/outputs.tf

ssh_config needed only for replicated tests
unique dns names

need only for replicated tests

---

main.tf
variables.tf

This change adds missing configuration options for TFE metrics that are present in other cloud implementations.
This change will be tested with the standard /test targets.

adding missing metrics config varliables

---

main.tf

Please include a one or two sentence description of what you're changing and why.
- This PR adds the Compute Engine API in the `activate_apis` variable that is passed into the `project_factory_project_services` module.
- Compute Engine API is required for the VM MIG, Image hosting and various other tasks.
Relates OR Closes #0000
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- Ran terraform `plan` on a fresh GCP project, and it would throw an error when attempting to read `data.google_compute_zones.available`, with the following: `Error: googleapi: Error 403: Compute Engine API has not been used in project ...`
* Terraform Version: 1.2.8
* Any additional relevant …

Add Compute Engine API to list of minimum APIs to enable on project

---

main.tf
variables.tf

Relates to [this utility module change](https://github.com/hashicorp/terraform-random-tfe-utility/pull/100/files)
This branch adds the `custom_agent_image_tag` variable using the changes in the PR above.
Tested in the [Azure module](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/206)

add custom_agent_image_tag

---

tests/standalone-external-rhel8-worker/data.tf
tests/standalone-external-rhel8-worker/locals.tf
tests/standalone-external-rhel8-worker/main.tf

#231 attempted to change the id of the gcp artifact registry to correct recent test failures but it failed, possibly because it targeted a registry in yet another project from the `slash` command tests in the PR.  This change makes the source project dynamic and based on the runtime gcp project id.

Using a project reference to generalize the running environment for the rhel8 worker test

---

modules/redis/main.tf

This pull request upgrades the officially supported redis version to 6 because 5 will be deprecated.

upgrade redis to 6.0

---

main.tf
modules/redis/main.tf
modules/redis/variables.tf
tests/private-active-active/main.tf
tests/private-tcp-active-active/main.tf
tests/public-active-active/main.tf
variables.tf

[TF-8869](https://hashicorp.atlassian.net/browse/TF-8869)
This test adds a variable for changing the redis version.
These tests are failing because of stale credentials, but the redis version part of it passes, as evidenced by the public-active-active test spinning it up successfully.
[TF-8869]: https://hashicorp.atlassian.net/browse/TF-8869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add redis_version variable

---

tests/private-active-active/main.tf
tests/private-tcp-active-active/main.tf
tests/public-active-active/main.tf
variables.tf

[Jira TF-8869](https://hashicorp.atlassian.net/browse/TF-8869) 
Relates: #264 
Redis creation fails with unspecified version pinning. This branch uses the pinned 7.0 version specified [here](https://cloud.google.com/memorystore/docs/redis/supported-versions) and approved [here on the docs](https://developer.hashicorp.com/terraform/enterprise/install/automated/active-active#appendix-2-gcp-memorystore-for-redis).
The test using `REDIS_6_X` [failed](https://github.com/hashicorp/terraform-google-terraform-enterprise/pull/265#issuecomment-1695970659) because it defaulted down to `6.0`, so I simply went up to `7.0` instead of pinning to 6 since we recommend v7. 
The proceeding three tests used `REDIS_7_0`, and the Redis creation in each passed. 
The failure in the `private-active-active` test …

specifiy redis version

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

This branch:
* updates the `setup-gcloud` actions
* brings parity between the variables in the `test` and `destroy` workflows
* uses `consolidated_services` mode for tests
This will be tested after merge.

update setup-gcloud actions

---

main.tf
tests/private-active-active/main.tf
tests/private-tcp-active-active/main.tf
tests/public-active-active/main.tf
variables.tf

#228 
[Jira TF-8869](https://hashicorp.atlassian.net/browse/TF-8869)
This branch adds variables for the `health_check` options available. Having these variables allows us to add more time to the health check to give TFE a bit more time to be installed and ready.
Tests passed below . The one `destroy` failure was because of exceeding a GCP rate limit, ruining my perfect test moment.

adds variables for health check options

---

main.tf

[Jira TF-5370](https://hashicorp.atlassian.net/browse/TF-5370)
[Jira TF-8611](https://hashicorp.atlassian.net/browse/TF-8611)

use tfe_init_legacy for Replicated installs

---

tests/standalone-external-rhel8-worker/variables.tf
tests/standalone-mounted-disk/variables.tf
variables.tf

#270 
This is a followup PR so that the `consolidated_services_enabled` variable is defaulted to `true`.

default consolidated_services to true

---

.github/workflows/handler-destroy.yml
.github/workflows/handler-test.yml

[TF-8611](https://hashicorp.atlassian.net/browse/TF-8611)
I am reverting the workflow refs to `main` since I [merged](https://github.com/hashicorp/terraform-random-tfe-utility/pull/133/files) `ah/tf-8611-gcp-fdo-1` of [terraform-random-tfe-utility](https://github.com/hashicorp/terraform-random-tfe-utility).
[TF-8611]: https://hashicorp.atlassian.net/browse/TF-8611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

revert workflow refs to main

---

main.tf

Relates: https://github.com/hashicorp/terraform-random-tfe-utility/pull/135
While testing a backup, @miguelhrocha discovered that the disk_path was not set for FDO deployments. It had gone unnoticed since we had not done a backup test yet using these modules as it was using the default docker mount.
Passing test below. Also, here you can see that the postgres data is on the instance.

add disk_path to docker_compose

---

main.tf
tests/private-active-active/locals.tf
tests/private-active-active/main.tf
tests/private-active-active/variables.tf
tests/private-tcp-active-active/locals.tf
tests/private-tcp-active-active/main.tf
tests/private-tcp-active-active/variables.tf
tests/public-active-active/locals.tf
tests/public-active-active/main.tf
tests/public-active-active/variables.tf
tests/standalone-external-rhel8-worker/locals.tf
tests/standalone-external-rhel8-worker/main.tf
tests/standalone-external-rhel8-worker/variables.tf
tests/standalone-mounted-disk/locals.tf
tests/standalone-mounted-disk/main.tf
tests/standalone-mounted-disk/variables.tf
variables.tf

[Jira TF-10844](https://hashicorp.atlassian.net/browse/TF-10844)
This branch updates the module to use the docker login changes introduced in https://github.com/hashicorp/terraform-random-tfe-utility/pull/137.
All module tests are updated to accommodate this change.
(I also took the liberty to alphabetize and a couple of small clean up tasks while I was in there.)
FDO tests have been run in comments below.

add var.registry

---

main.tf
modules/database/versions.tf
modules/load_balancer/versions.tf
modules/networking/versions.tf
modules/object_storage/versions.tf
modules/private_load_balancer/versions.tf
modules/private_tcp_load_balancer/versions.tf
modules/redis/versions.tf
modules/service_accounts/versions.tf
variables.tf
versions.tf

This PR changes the root module and its submodules to upgrade the `hashicorp/google` and `hashicorp/google-beta` to rely on the v5 version.
The PR introduces the capability to attach public IPs to the instances created by the mig to enable ssh operations in the context of release testing. The variable that controls this flow is called `enable_public_ssh_access`.

[TF-10424] Upgrade google provider constraints to v5

---

main.tf
modules/networking/main.tf
variables.tf

This PR adds an additional optional variable to disable usage reporting to HashiCorp census service.

add usage_reporting_opt_out variable

---

main.tf
tests/private-active-active/main.tf
tests/private-active-active/variables.tf
tests/private-tcp-active-active/main.tf
tests/private-tcp-active-active/variables.tf
tests/public-active-active/main.tf
tests/public-active-active/variables.tf
tests/standalone-external-rhel8-worker/main.tf
tests/standalone-external-rhel8-worker/variables.tf
tests/standalone-mounted-disk/main.tf
tests/standalone-mounted-disk/variables.tf
variables.tf

This change removes non-consolidated mode settings. This change will be tested in dev-infra upon merge of the changes removing non-consolidated mode capability in the core product.

Removes non-consolidated service settings.

---

main.tf

Propagates the `ext_vault_runtime_config` to the FDO runtime_engine_config.

Add vault_token_renew value to runtime_config

---

modules/database/main.tf

This change enables the generation of database passwords with special characters which is enabled by: https://github.com/hashicorp/terraform-random-tfe-utility/pull/156
This has been tested through development environment instances.  This change will be recertified against this PR before merging.

Using database special characters

---

main.tf

The Google provider set a limitation that either `max_unavailable_fixed` or `max_surge_fixed` has to be set, but at least one of them has to have a value. 
`max_unavailable_fixed` is already set in the case of Replicated, so I thought why not set it for FDO too?

[TF-16084] Set max_unavailable_fixed in both FDO and replicated

---

modules/networking/main.tf

It is unclear to me why this is failing now, maybe Google did something that doesn't relect on the provider. However, we may not need this anymore due to a fix in the v5 provider:
https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/guides/version_5_upgrade#terraform-destroy-now-fully-deletes-the-resource-instead-of-abandoning

[TF-16084] Remove deletion_policy in google_service_networking_connection

---

locals.tf
main.tf
variables.tf

If we wish to deploy Terraform Enterprise with an external database, but reuse an existing database, we need to be able to pass both the host and the password. 
Context: https://hashicorp.atlassian.net/browse/TF-18440
This has been tested in postgres failover tests, using a patroni cluster deployed separately, such as in this module: https://github.com/hashicorp/tf-onprem-dev-infra/blob/bc01989032fa5adc54635891506b88a97a5fa6be/modules/nikolasrieble/HAPG_docker_patroni.tf#L64

Feature: Introduce variables database_host and database_password
